# Generated by Django 3.0.3 on 2020-07-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sum_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='sum',
            name='month',
            field=models.IntegerField(default=None),
        ),
    ]
