# Generated by Django 3.0.3 on 2020-07-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sum_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sum',
            name='id',
        ),
        migrations.AddField(
            model_name='sum',
            name='sumID',
            field=models.AutoField(db_column='sumID', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
