# Generated by Django 3.0.3 on 2020-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200729_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sum',
            name='sumID',
        ),
        migrations.AddField(
            model_name='sum',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
