# Generated by Django 3.0.3 on 2020-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200729_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sum',
            name='id',
        ),
        migrations.AddField(
            model_name='sum',
            name='sumid',
            field=models.AutoField(db_column='sumid', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
