# Generated by Django 3.0.3 on 2020-08-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='accountid',
            field=models.AutoField(db_column='accountid', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
