# Generated by Django 3.0.3 on 2020-08-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200828_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sum',
            name='kategori',
        ),
        migrations.AddField(
            model_name='sum',
            name='account',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.Account'),
        ),
    ]
